# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bike',
            },
        ),
        migrations.CreateModel(
            name='PriceByFrecuency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently', models.SmallIntegerField(choices=[(2, 'Daily'), (3, 'weekly'), (1, 'Hourly')], default=1)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'price_by_frecuency',
            },
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neto_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('familiar_rental_promotion', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rentals',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='price_by_frecuency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bike', to='rents.PriceByFrecuency'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rentals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_bike', to='rents.Rentals'),
        ),
    ]
