# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price_by_frecuency',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='rent',
        ),
        migrations.AddField(
            model_name='rent',
            name='price_by_frecuency',
            field=models.ManyToManyField(to='rents.PriceByFrecuency'),
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
