# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20180201_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('price_by_frecuency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.PriceByFrecuency')),
            ],
            options={
                'db_table': 'bike',
            },
        ),
        migrations.RemoveField(
            model_name='rent',
            name='price_by_frecuency',
        ),
        migrations.AddField(
            model_name='rent',
            name='familiar_rental_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='neto_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Rent'),
        ),
    ]
